export const menus = [
  {
    menu_aid: 1,
    menu_title: "2pc Chickenjoy",
    menu_category: "Chickenjoy",
    menu_price: "200",
    menu_image: "chicken-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 2,
    menu_title: "3pc Chickenjoy",
    menu_category: "Chickenjoy",
    menu_price: "280",
    menu_image: "chicken-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 3,
    menu_title: "2pcs Fries Bucket Chickenjoy",
    menu_category: "Chickenjoy",
    menu_price: "300",
    menu_image: "chicken-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 4,
    menu_title: "Family Spaghetti Bucket Chickenjoy",
    menu_category: "Chickenjoy",
    menu_price: "450",
    menu_image: "chicken-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 5,
    menu_title: "1x Fries Bucket Chickenjoy",
    menu_category: "Chickenjoy",
    menu_price: "260",
    menu_image: "chicken-5.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 6,
    menu_title: "8pcs Bucket Chickenjoy",
    menu_category: "Chickenjoy",
    menu_price: "550",
    menu_image: "chicken-6.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 7,
    menu_title: "Chicken Burger w/ Fries",
    menu_category: "Value Meal",
    menu_price: "180",
    menu_image: "value-meal-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 8,
    menu_title: "Cheeze Chicken Burger",
    menu_category: "Value Meal",
    menu_price: "200",
    menu_image: "value-meal-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 9,
    menu_title: "2pc Chicken w/ Peach Mango Pie",
    menu_category: "Value Meal",
    menu_price: "210",
    menu_image: "value-meal-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 10,
    menu_title: "2pc 8pc Bucket Chicken w/ 3pc Peach Mango Pie",
    menu_category: "Value Meal",
    menu_price: "250",
    menu_image: "value-meal-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 11,
    menu_title: "2pc Cheeze Chicken Burger w/ Fries",
    menu_category: "Value Meal",
    menu_price: "250",
    menu_image: "value-meal-5.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 11,
    menu_title: "2pc Cheeze Chicken Burger w/ Fries",
    menu_category: "Value Meal",
    menu_price: "250",
    menu_image: "value-meal-5.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 12,
    menu_title: "Jolly Spaghetti Solo",
    menu_category: "Spaghetti",
    menu_price: "250",
    menu_image: "spag-1.webp",
    menu_is_active: true },
  {
    menu_aid: 13,
    menu_title: "Jolly Spaghetti w/ Chicken",
    menu_category: "Spaghetti",
    menu_price: "250",
    menu_image: "spag-2.webp",
    menu_is_active: true },
  {
    menu_aid: 14,
    menu_title: "Burger Steak w/ Rice",
    menu_category: "Burger Steak",
    menu_price: "250",
    menu_image: "steak-1.webp",
    menu_is_active: true  },
  {
    menu_aid: 15,
    menu_title: "Family Pan Burger Steak",
    menu_category: "Burger Steak",
    menu_price: "290",
    menu_image: "steak-2.webp",
    menu_is_active: true  },
  {
    menu_aid: 16,
    menu_title: "Palabok Solo",
    menu_category: "Palabok",
    menu_price: "180",
    menu_image: "palabok-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 17,
    menu_title: "Palabok w/ Drinks",
    menu_category: "Palabok",
    menu_price: "190",
    menu_image: "palabok-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 18,
    menu_title: "Fries",
    menu_category: "Sides",
    menu_price: "60",
    menu_image: "sides-1.webp",
    menu_is_active: true  },
  {
    menu_aid: 19,
    menu_title: "Mashed Potato",
    menu_category: "Sides",
    menu_price: "70",
    menu_image: "sides-2.webp",
    menu_is_active: true  },
  {
    menu_aid: 20,
    menu_title: "Mango Pie",
    menu_category: "Desserts",
    menu_price: "50",
    menu_image: "dessert-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 21,
    menu_title: "Ube Pie",
    menu_category: "Desserts",
    menu_price: "50",
    menu_image: "dessert-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 22,
    menu_title: "Yumburger",
    menu_category: "Burger",
    menu_price: "40",
    menu_image: "burger-1.webp",
    menu_is_active: true
  },
  {
    menu_aid: 23,
    menu_title: "Yumburger w/ Fries",
    menu_category: "Burger",
    menu_price: "60",
    menu_image: "burger-2.webp",
    menu_is_active: true
  },
  {
    menu_aid: 24,
    menu_title: "Cheesy Yumburger w/ Fries",
    menu_category: "Burger",
    menu_price: "70",
    menu_image: "burger-4.webp",
    menu_is_active: true
  },
  {
    menu_aid: 25,
    menu_title: "Cheesy Yumburger",
    menu_category: "Burger",
    menu_price: "70",
    menu_image: "burger-3.webp",
    menu_is_active: true
  },
  {
    menu_aid: 26,
    menu_title: "Double Cheesy Yumburger",
    menu_category: "Burger",
    menu_price: "80",
    menu_image: "burger-5.webp",
    menu_is_active: true
  },
  {
    menu_aid: 27,
    menu_title: "Burger Meal",
    menu_category: "Burger",
    menu_price: "80",
    menu_image: "burger-6.webp",
    menu_is_active: true
  },
  {
    menu_aid: 27,
    menu_title: "Burger Deluxe",
    menu_category: "Burger",
    menu_price: "90",
    menu_image: "burger-7.webp",
    menu_is_active: true
  },
  {
    menu_aid: 27,
    menu_title: "Burger Deluxe w/ Fries",
    menu_category: "Burger",
    menu_price: "99",
    menu_image: "burger-8.webp",
    menu_is_active: true
  },
  {
    menu_aid: 28,
    menu_title: "Family Pan Burger Steak w/ Chicken Meal",
    menu_category: "Burger Steak",
    menu_price: "99",
    menu_image: "steak-3.webp",
    menu_is_active: true  },
  {
    menu_aid: 29,
    menu_title: "Family Pan Jolly Spaghetti",
    menu_category: "Spaghetti",
    menu_price: "160",
    menu_image: "spag-3.webp",
    menu_is_active: true },
  {
    menu_aid: 30,
    menu_title: "Peach Mango Pie",
    menu_category: "Desserts",
    menu_price: "30",
    menu_image: "dessert-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 31,
    menu_title: "Pineapple",
    menu_category: "Desserts",
    menu_price: "30",
    menu_image: "dessert-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 32,
    menu_title: "Pepsi",
    menu_category: "Desserts",
    menu_price: "30",
    menu_image: "dessert-5.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 33,
    menu_title: "Rice",
    menu_category: "Sides",
    menu_price: "30",
    menu_image: "sides-3.webp",
    menu_is_active: true  },
  {
    menu_aid: 34,
    menu_title: "Adobo Rice",
    menu_category: "Sides",
    menu_price: "30",
    menu_image: "sides-4.webp",
    menu_is_active: true  },
  {
    menu_aid: 35,
    menu_title: "Spaghetti",
    menu_category: "Sides",
    menu_price: "50",
    menu_image: "sides-5.webp",
    menu_is_active: true  },
];